### ISSUE TITLE
create the bug reporter view

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#29]
refer to the feature spec https://github.com/unfoldingWord-dev/ts-requirements/tree/master/features

**Comment by neutrinog** [comment]
We need to add a menu item for sending feedback. It can just be called "Feedback" in the menu.
In it the user should be able to submit some notes. There should already be a module written up for communicating with github. Just in case, here is an example of we we should see on github after someone submits a bug report.

---
Notes
======
sharing

Environment
======
Environment Key | Value
:----: | :----:
version | 3.1.0
build | 108
UDID | 508a51661fa34a9c
Android Release | 5.0.2
Android SDK | 21
Brand | lge
Device | e9wifi
Log history
======
```java
12/1/15 10:45 PM  E/com.door43.translationstudio.service.BroadcastListenerService: Broadcast listener encountered an exception
java.net.SocketException: Socket closed
	at libcore.io.Posix.recvfromBytes(Native Method)
	at libcore.io.Posix.recvfrom(Posix.java:161)
	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
	at java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:163)
	at java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:171)
	at java.net.DatagramSocket.receive(DatagramSocket.java:274)
	at java.nio.DatagramChannelImpl$DatagramSocketAdapter.receive(DatagramChannelImpl.java:597)
	at com.door43.translationstudio.network.BroadcastListenerRunnable.run(BroadcastListenerRunnable.java:64)
	at java.lang.Thread.run(Thread.java:818)

12/1/15 10:45 PM  E/com.door43.translationstudio.newui.ShareWithPeerDialog: Client service encountered an exception: failed to connect to /192.168.1.104 (port 38413): connect failed: EHOSTUNREACH (No route to host)
java.net.ConnectException: failed to connect to /192.168.1.104 (port 38413): connect failed: EHOSTUNREACH (No route to host)
	at libcore.io.IoBridge.connect(IoBridge.java:124)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:163)
	at java.net.Socket.startupSocket(Socket.java:593)
	at java.net.Socket.<init>(Socket.java:229)
	at com.door43.translationstudio.service.ClientService$ServerThread.run(ClientService.java:444)
	...
```
